---
- name: Install iptables-persistent package
  apt:
    name: iptables-persistent
    update_cache: yes

- name: Copy iptables template rules to /etc/iptables
  template:
    src: iptables/rules.v4.j2
    dest: /etc/iptables/rules.v4
  notify: restore iptables
