---
- name: Iptables Hardening
  import_tasks: iptables.yml

- name: netplan apply
  import_tasks: netplan.yml
  
- name: Install resolvconf on gateway
  apt:
    name:
      - resolvconf
    update_cache: yes

- name: Add DNS Addresses
  blockinfile:
    path: /etc/resolvconf/resolv.conf.d/head
    block: |
      nameserver 8.8.8.8
      nameserver 1.1.1.1
  notify: restart resolvconf

- name: Set ip_forward
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    reload: yes

