---
- name: Iptables Hardening
  import_tasks: iptables.yml

- name: netplan apply
  import_tasks: netplan.yml

- name: Set ip_forward
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    reload: yes

- name: Copy hosts file
  template:
    src: hosts/hosts.j2
    dest: /etc/hosts

