---
- name: netplan apply
  import_tasks: netplan.yml

- name: Install resolvconf on gateway
  apt:
    name:
      - resolvconf
    update_cache: yes

- name: Add DNS Addresses
  blockinfile:
    path: /etc/resolvconf/resolv.conf.d/head
    block: |
      nameserver 8.8.8.8
      nameserver 1.1.1.1
  notify: restart resolvconf

- name: install HAProxy
  apt:
    name:
      - haproxy
    update_cache: yes

- name: Append the frontend and backend lines to /etc/haproxy/haproxy.cfg
  template:
    src: config/haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy service

