---
- name: netplan apply
  import_tasks: netplan.yml

- name: install HAProxy
  apt:
    name:
      - haproxy
    update_cache: yes

- name: Append the frontend and backend lines to /etc/haproxy/haproxy.cfg
  template:
    src: config/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy service

