apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv
  namespace: apache-kafka
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /root/kafka