apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    name: kafka
spec:
  ports:
  - name: kafka-port
    port: "{{ kafka_port }}"
    protocol: "{{ protocol }}"
  selector:
    app: kafka
    id: "0"
  type: "{{ kafka_type }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker0
spec:
  replicas: "{{ replica }}"
  selector:
    matchLabels:
      app: kafka
      id: "0"
  template:
    metadata:
      labels:
        app: kafka
        id: "0"
    spec:
      containers:
      - name: kafka
        image: 94.101.187.195:5000/wurstmeister/kafka
        ports:
        - containerPort: "{{ kafka_port }}"
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-service:{{ zookeeper_client_port }}
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka-service.default.svc.cluster.local
        - name: KAFKA_CREATE_TOPICS
          value: input:1:1, output:1:1