apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
  namespace: apache-kafka
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '9308'
spec:
  selector:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kafka-exporter
  ports:
  - name: http-metrics
    protocol: TCP
    port: 9308
    targetPort: 9308
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kafka-exporter
  name: kafka-exporter
  namespace: apache-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: kafka-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: kafka-exporter
    spec:
      containers:
      - name: kaka-exporter
        image: dockerhub.ir/danielqsj/kafka-exporter:latest
        args:
          - '--kafka.server=kafka-service.apache-kafka.svc.cluster.local:9092'
        ports:
          - containerPort: 9308