apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: apache-kafka
  labels:
    app: zookeeper-1
spec:
  ports:
  - name: client
    port: {{ zookeeper_client_port }}
    protocol: {{ protocol }}
  - name: follower
    port: {{ zookeeper_follower_port }}
    protocol: {{ protocol }}
  - name: leader
    port: {{ zookeeper_leader_port }}
    protocol: {{ protocol }}
  selector:
    app: zookeeper-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deploy
  namespace: apache-kafka
spec:
  replicas: {{ replica }}
  selector:
    matchLabels:
      app: zookeeper-1
  template:
    metadata:
      labels:
        app: zookeeper-1
    spec:
      containers:
      - name: zookeeper-service
        image: dockerhub.ir/bitnami/zookeeper
        ports:
        - containerPort: {{ zookeeper_client_port }}
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: zookeeper-service
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "true"