---

# links
kubernetes_add_gpg_key: https://packages.cloud.google.com/apt/doc/apt-key.gpg
docker_add_gpg_key: https://download.docker.com/linux/ubuntu/gpg

kubernetes_repo_url: https://apt.kubernetes.io/
docker_repo_url: https://download.docker.com/linux/ubuntu

# version
kubeadm_version: 1.19.2-00
kubelet_version: 1.19.2-00
kubectl_version: 1.19.2-00