---
monitor_manifest: 
  - "create-namespace.yml"
  - "monitor-pv.yml"
  - "monitor-pvc.yml"
  - "clusterRole.yaml"
  - "configMap-prometheus.yaml"
  - "configMap-datasource.yml"
  - "configMap-dashboards.yml"
  - "prometheus-manifest.yml"
  - "grafana-manifest.yml"
  - "node-exporter-manifest.yml"
  - "kube-state-metrics.yml"

prometheus_port: 9090
prometheus_node_port: 32001

grafana_port: 3000
grafana_node_port: 32002

type: NodePort
protocol: TCP
replica: 1