---
- name: Install packages that allow apt to be used over HTTPS
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Add an apt signing key for Docker
  apt_key:
    url: "{{ docker_add_gpg_key }}"
    state: present

- name: Add apt repository for stable version
  apt_repository:
    repo: "deb [arch=amd64] {{ docker_repo_url }} xenial stable"
    state: present

- name: Install docker and its dependecies
  apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io

- name: docker login
  docker_login:
    username: "{{ docker_username }}"
    password: "{{ docker_password }}"

- name: pull an images for calico
  docker_image:
    name: "{{ item }}"
    source: pull
  loop:
    - calico/kube-controllers:v3.15.5
    - calico/node:v3.15.5
    - calico/pod2daemon-flexvol:v3.15.5
    - calico/cni:v3.15.5