---
- name: Install docker and its dependecies
  apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - docker
    - docker.io
    - python3-docker

- name: docker login
  docker_login:
    username: "{{ docker_username }}"
    password: "{{ docker_password }}"

- name: pull an images for calico
  docker_image:
    name: "dockerhub.ir/{{ item }}:{{ calico_version }}"
    source: pull
  loop: "{{ calico_docker_pull }}"
  notify: change docker name