---
- name: netplan apply
  import_tasks: netplan.yml

- name: Disable swap
  import_tasks: swap.yml

- name: Install Docker
  import_tasks: docker.yml

- name: Install Kubeadm, Kubelet, Kubectl
  import_tasks: kube.yml

