---
- name: create directory for kafka mnifests
  file:
    path: /root/apache-kafka
    state: directory
    owner: root
    group: root
    mode: 0755

- name: copy manifests into apache-kafka directory
  template:
    src: "{{ item }}"
    dest: "/root/apache-kafka/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ kafka_manifest }}"
  notify: apply kubernetes manifests