---
kafka_manifest: 
  - "create-namespace.yml"
  - "apache-kafka-pv.yml"
  - "apache-kafka-pvc.yml"
  - "zookeeper-manifest.yml"
  - "kafka-manifest.yml"
  - "producer-consumer.yml"
  - "kafka-exporter.yml"

# ports
kafka_port: 9092
zookeeper_client_port: 2181
zookeeper_follower_port: 2888
zookeeper_leader_port: 3888

kafka_type: LoadBalancer
protocol: TCP
replica: 1