---
- name: apply netplan
  command: netplan apply
  async: 45
  poll: 0

- name: Restart kubelet
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted

- name: docker status
  service:
    name: docker
    state: started

- name: change docker name
  command: docker tag dockerhub.ir/{{ item }}:{{ calico_version }} {{ item }}:{{ calico_version }}
  loop: "{{ calico_docker_pull }}"