apiVersion: v1
kind: ConfigMap
metadata:
  name: granafa-server-conf
  labels:
    name: granafa-server-conf
  namespace: monitoring
data:
  datasource.yml: |-
    apiVersion: 1
    datasources:
    - name: prometheusdata
      type: prometheus
      access: proxy
      orgId: 1
      url: "{{ prometheus_url }}"
      user: "{{ grafana_username }}"
      secureJsonData:
        password: "{{ grafana_password }}"
      isDefault: true
    