apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-config-pv
  namespace: monitoring
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /root/prometheus-config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-storage-pv
  namespace: monitoring
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /root/prometheus-storage