apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
  labels:
    name: prometheus
spec:
  ports:
  - protocol: {{ protocol }}
    port: {{ prometheus_port }}
    targetPort: {{ prometheus_port }}
    nodePort: {{ prometheus_node_port }}
  selector:
    app: prometheus
  type: {{ type }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-broker0
  namespace: monitoring
spec:
  replicas: {{ replica }}
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: dockerhub.ir/prom/prometheus
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--storage.tsdb.path=/prometheus"
        ports:
        - containerPort: {{ prometheus_port }}
